#!/usr/bin/env sh
npm run bundle
cd android/
./gradlew assembleDebug
cd ..
cp android/app/build/outputs/apk/debug/app-debug.apk __tests__/app-debug.apk
cd ../
git add .
git commit -m "$1"
git push
cd APP/